spring:
  main:
    web-application-type: none
  rabbitmq:
    host: rabbitmq3
    username: myuser
    password: mypassword
    port: 15672
    deliveryExchange: delivery.exchange
    deliveryQueue: delivery.queue
    deliveryRoutingKey: delivery.routingKey
    adjustmentExchange: adjustment.exchange
    adjustmentQueue: adjustment.queue
    adjustmentRoutingKey: adjustment.routingKey
    bonusExchange: bonus.exchange
    bonusQueue: bonus.queue
    bonusRoutingKey: bonus.routingKey
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: user
    password: password
  sql:
    init:
      mode: always
