openapi: 3.0.3
info:
  title: Statements Service API
  description: Statements Calculation Service API
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/'
paths:
  /couriers/{id}/statements: # todo adjust with query params for period of time
    get:
      tags:
        - statements
      operationId: "getStatements"
      summary: "Retrieves statements for specified courier"
      parameters:
        - name: id
          in: path
          required: true
          description: The courierId to calculate statements for
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatementsResponse'
        "404":
          description: Courier not found
components:
  schemas:
    StatementsResponse:
      type: object
