version: '2.2'

services:

  rabbitmq3:
    image: rabbitmq:3-management
    container_name: rabbit-skip-statements
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword

  db:
    image: mysql:5.7
    container_name: mysql-skip-statements-db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    ports:
      - '${DB_PORT}:3306'
    expose:
      - '${DB_PORT}'
    volumes:
      - db_data:/var/lib/mysql

  couriers-web-app:
    image: couriers-web-app
    container_name: couriers-web-app
    build:
      context: .
      dockerfile: ./couriers-web-app/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?autoReconnect=true&useSSL=false
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '${APP_PORT}:8080'
    expose:
      - '${APP_PORT}'

  couriers-event-consumer:
    image: couriers-event-consumer
    container_name: couriers-event-consumer
    build:
      context: .
      dockerfile: ./couriers-event-consumer/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?autoReconnect=true&useSSL=false
    depends_on:
      db:
        condition: service_healthy
      rabbitmq3:
        condition: service_started

  couriers-event-producer:
    image: couriers-event-producer
    container_name: couiriers-event-producer
    build:
      context: .
      dockerfile: ./couriers-event-producer/Dockerfile
    depends_on:
      rabbitmq3:
        condition: service_started
      couriers-event-consumer:
        condition: service_started
    ports:
      - '8081:8081'
    expose:
      - '8081'

volumes:
  db_data:
