server:
  port: 8081

spring:
  rabbitmq:
    host: rabbitmq3
    username: myuser
    password: mypassword
    port: 15672
    deliveryExchange: delivery.exchange
    deliveryQueue: delivery.queue
    deliveryRoutingKey: delivery.routingKey
    adjustmentExchange: adjustment.exchange
    adjustmentQueue: adjustment.queue
    adjustmentRoutingKey: adjustment.routingKey
    bonusExchange: bonus.exchange
    bonusQueue: bonus.queue
    bonusRoutingKey: bonus.routingKey
