openapi: 3.0.3
info:
  title: Couriers Service API
  description: Couriers Service API
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/'
paths:
  /couriers/{id}/deliveries:
    get:
      tags:
        - couriers
      operationId: "getCourierDeliveries"
      summary: "Returns delivery transactions by period and courier"
      parameters:
        - name: id
          in: path
          required: true
          description: The courierId to calculate statements for
          schema:
            type: string
        - name: start
          in: query
          required: true
          description: Timeframe starting from. Format "yyyy-MM-dd HH:mm:ss"
          schema:
            type: string
        - name: end
          in: query
          required: true
          description: Timeframe ends by. Format "yyyy-MM-dd HH:mm:ss"
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeliveryTransactionsResponse'
        "404":
          description: courier not found
  /couriers/{id}/statements:
    get:
      tags:
        - couriers
      operationId: "getCourierStatement"
      summary: "Retrieves weekly statement for specified courier by default, for timeframe if provided"
      parameters:
        - name: id
          in: path
          required: true
          description: The courierId to calculate statements for
          schema:
            type: string
        - name: start
          in: query
          required: false
          description: Timeframe starting from. Format "yyyy-MM-dd HH:mm:ss"
          schema:
            type: string
        - name: end
          in: query
          required: false
          description: Timeframe ends by. Format "yyyy-MM-dd HH:mm:ss"
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatementResponse'
        "404":
          description: Courier not found
components:
  schemas:
    StatementResponse:
      type: object
      required:
        - value
        - statementId
      properties:
        sum:
          type: number
        deliveryRecordIds:
          type: array
          items:
            type: string
        deliveryIds:
          type: array
          items:
            type: string
    DeliveryResponse:
      type: object
      required:
        - deliveryId
        - sum
      properties:
        sum:
          type: number
        deliveryId:
          type: string
    DeliveryTransactionsResponse:
      type: object
      required:
        - from
        - to
        - numberOfTransactions
        - courierId
      properties:
        courierId:
          type: string
        from:
          type: string
        to:
          type: string
        numberOfTransactions:
          type: integer
        deliveries:
          type: array
          items:
            $ref: '#/components/schemas/DeliveryResponse'
