openapi: 3.0.3
info:
  title: Events Models API
  description: Consuming Events API
  version: 1.0.0
paths:
  /fake:
    get:
      operationId: "fake"
      responses:
        "200":
          description: success
components:
  schemas:
    DeliveryCreatedEvent:
      type: object
      required:
        - deliveryId
        - courierId
        - createdTimestamp
        - value
      properties:
        deliveryId:
          type: string
        courierId:
          type: string
        createdTimestamp:
          type: string
        value:
          type: number
    AdjustmentModifiedEvent:
      type: object
      required:
        - deliveryId
        - adjustmentId
        - modifiedTimestamp
        - value
      properties:
        deliveryId:
          type: string
        adjustmentId:
          type: string
        modifiedTimestamp:
          type: string
        value:
          type: number
    BonusModifiedEvent:
      type: object
      required:
        - deliveryId
        - bonusId
        - modifiedTimestamp
        - value
      properties:
        deliveryId:
          type: string
        bonusId:
          type: string
        modifiedTimestamp:
          type: string
        value:
          type: number
